package bmcc

var Payloads = []*Bawang{{
	ID					: `p0`,
	BenihAsetID			: `benih0`,
	BawangAsetID		: `bawang0`,
	UsernamePengirim	: `Brata`,
	UsernamePenerima	: `Maharani`,
	AlamatPengirim		: `Brebes`,
	AlamatPenerima		: `Bogor`,
	KuantitasBenihKg	: 5,
	HargaBenihPerKg		: 10000,
	HargaBenihTotal		: 50000,
	KuantitasBawangKg	: 10,
	HargaBawangPerKg	: 20000,
	HargaBawangTotal	: 200000,
	CreatedAt			: 1625037898,
	UmurBenih			: `2 hari`,
	UmurPanen			: `5 hari`,
	LamaPenyimpanan		: `7 hari`,
	Varietas			: `Bima Brebes`,
	UkuranUmbi			: `besar`,
	KadarAirPersen		: 50,
	Pupuk				: `NPK`,
	Pestisida			: `Akarisida`,
	Perlakuan			: `-`,
	Produktivitas		: `-`,
	TanggalTanam		: 1625037900,
	TanggalPanen		: 1625037946,
	TanggalMasuk		: 1625038214,
	TeknikSorting		: `Ukuran Umbi`,
	MetodePengemasan	: `Karung`,
	TxID1				: `t01`,
	TxID2				: `t02`,
	TxID3				: `t03`,
	IsAsset				: true,
	IsConfirmed			: false,
	IsEmpty				: false,
	IsRejected			: false,
}, {
	ID					: `p1`,
	BenihAsetID			: `benih1`,
	BawangAsetID		: `bawang1`,
	UsernamePengirim	: `Brata`,
	UsernamePenerima	: `Maharani`,
	AlamatPengirim		: `Brebes`,
	AlamatPenerima		: `Bogor`,
	KuantitasBenihKg	: 5,
	HargaBenihPerKg		: 10000,
	HargaBenihTotal		: 50000,
	KuantitasBawangKg	: 10,
	HargaBawangPerKg	: 20000,
	HargaBawangTotal	: 200000,
	CreatedAt			: 1625037898,
	UmurBenih			: `2 hari`,
	UmurPanen			: `5 hari`,
	LamaPenyimpanan		: `7 hari`,
	Varietas			: `Bima Brebes`,
	UkuranUmbi			: `besar`,
	KadarAirPersen		: 50,
	Pupuk				: `NPK`,
	Pestisida			: `Akarisida`,
	Perlakuan			: `-`,
	Produktivitas		: `-`,
	TanggalTanam		: 1625037900,
	TanggalPanen		: 1625037946,
	TanggalMasuk		: 1625038214,
	TeknikSorting		: `Ukuran Umbi`,
	MetodePengemasan	: `Karung`,
	TxID1				: `t11`,
	TxID2				: `t12`,
	TxID3				: `t13`,
	IsAsset				: false,
	IsConfirmed			: true,
	IsEmpty				: false,
	IsRejected			: false,
}, {
	ID					: `p2`,
	BenihAsetID			: `benih2`,
	BawangAsetID		: `bawang2`,
	UsernamePengirim	: `Brata`,
	UsernamePenerima	: `Maharani`,
	AlamatPengirim		: `Brebes`,
	AlamatPenerima		: `Bogor`,
	KuantitasBenihKg	: 5,
	HargaBenihPerKg		: 10000,
	HargaBenihTotal		: 50000,
	KuantitasBawangKg	: 10,
	HargaBawangPerKg	: 20000,
	HargaBawangTotal	: 200000,
	CreatedAt			: 1625037898,
	UmurBenih			: `2 hari`,
	UmurPanen			: `5 hari`,
	LamaPenyimpanan		: `7 hari`,
	Varietas			: `Bima Brebes`,
	UkuranUmbi			: `besar`,
	KadarAirPersen		: 50,
	Pupuk				: `NPK`,
	Pestisida			: `Akarisida`,
	Perlakuan			: `-`,
	Produktivitas		: `-`,
	TanggalTanam		: 1625037900,
	TanggalPanen		: 1625037946,
	TanggalMasuk		: 1625038214,
	TeknikSorting		: `Ukuran Umbi`,
	MetodePengemasan	: `Karung`,
	TxID1				: `t21`,
	TxID2				: `t22`,
	TxID3				: `t23`,
	IsAsset				: false,
	IsConfirmed			: true,
	IsEmpty				: false,
	IsRejected			: false,
}, }